# ????????????????????
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true
# QQ OpenSDK?tencent_kit???? android.support.v4?? Jetifier ?? AndroidX
android.enableJetifier=true
android.nonTransitiveRClass=true

kotlin.code.style=official
# ??? D:?Pub ??? C: ??Kotlin ???????????
kotlin.incremental=false
kotlin.caching.enabled=false
